## Instructions

#### 。 This homework has two parts
    1. There are 6 simple questions, just follow the instrctions and get the same output as the following.
    2. It's how simple neural networks working. As the same as part 1, just follow the instructions and get the same output

#### 。 All of this homework should use Numpy or Pandas

#### 。 Please follow the same variable name as the instuctions of every questions 

## Part 1

**1. Import both numpy and pandas packages**

In [2]:
import numpy as np
import pandas as pd

**2. Create a 3x3 matrix with values ranging from 0 to 8**

In [2]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**3. Create a 5x5 matrix with row values ranging from 0 to 4**

In [3]:
a=np.arange(0,5)
a1=np.append(a,a)
a2=np.append(a1,a1)
a3=np.append(a2,a)
a3.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**4. How to swap the first and second rows of a**

In [4]:
a = np.arange(25).reshape(5,5)
a[[0,1],:]=a[[1,0],:]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**5. Give two ways to show how to get the n largest values of a (no sort the value is fine)**

In [5]:
# Don't need to change this cell
a = np.arange(100)
np.random.shuffle(a)
n = 5

In [6]:
# Way 1
a
a1=np.argpartition(a, -5)[-5:]
a[a1]

array([95, 96, 97, 99, 98])

In [7]:
# Way 2
a=np.sort(a)
a.reshape(20,5)
a[95:]

array([95, 96, 97, 98, 99])

**6. Compare if array a and array b is totally the same**

In [8]:
np.random.seed(123)
a = np.round(np.random.random(100)*100, 0)
b = np.random.randint(1, 100, 100)

# Put your code here
a=np.sort(a)
b=np.sort(b)
print(a==b)

[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False]


## Part 2

### Online Shoppers Purchasing Intention Dataset

The dataset consists of 10 numerical and 8 categorical attributes. The 'Revenue' attribute can be used as the class label.

* ``0 Administrative``, ``1 Administrative Duration``, ``2 Informational``, ``3 Informational Duration``, ``4 Product Related`` and ``5 Product Related Duration`` - represent the number of different types of pages visited by the visitor in that session and total time spent in each of these page categories. The values of these features are derived from the URL information of the pages visited by the user and updated in real time when a user takes an action, e.g. moving from one page to another. 


* ``6 Bounce Rate``, ``7 Exit Rate`` and ``8 Page Value`` - represent the metrics measured by "Google Analytics" for each page in the e-commerce site. The value of "Bounce Rate" feature for a web page refers to the percentage of visitors who enter the site from that page and then leave ("bounce") without triggering any other requests to the analytics server during that session. The value of "Exit Rate" feature for a specific web page is calculated as for all pageviews to the page, the percentage that were the last in the session. The "Page Value" feature represents the average value for a web page that a user visited before completing an e-commerce transaction. 


* ``9 Special Day`` - indicates the closeness of the site visiting time to a specific special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8. 


* The dataset also includes ``11 operating system``, ``12 browser``, ``13 region``, ``14 traffic type``, ``15 visitor type`` as returning or new visitor, a Boolean value indicating whether the date of the visit is ``16 weekend``, and ``9 month of the year``.


---
* **``17 Revenue``** - binary labels



* More information of this data: [UCI | Online Shoppers Purchasing Intention Dataset](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset#)

**Use pandas to import the data and check the shape of dataset and save it as `" shoppers "`**

In [3]:
shoppers=pd.read_csv('D:/online_shoppers_intention.csv')
print(shoppers.shape)

(12330, 18)


**Use pandas function to let label be numeric as below and save it as `" label "`**

In [4]:
label=shoppers[['Revenue']]
label=np.array(label)
label=label.astype(int)
label=label.reshape(1,12330)
label

array([[0, 0, 0, ..., 0, 0, 0]])

**See some information of this data**

In [5]:
shoppers.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [6]:
x=shoppers[['Administrative','Administrative_Duration','Informational','Informational_Duration','ProductRelated','ProductRelated_Duration','BounceRates','ExitRates','PageValues','SpecialDay','OperatingSystems','Browser','Region','TrafficType']]
x.describe()

Administrative  Administrative_Duration  Informational  \
count    12330.000000             12330.000000   12330.000000   
mean         2.315166                80.818611       0.503569   
std          3.321784               176.779107       1.270156   
min          0.000000                 0.000000       0.000000   
25%          0.000000                 0.000000       0.000000   
50%          1.000000                 7.500000       0.000000   
75%          4.000000                93.256250       0.000000   
max         27.000000              3398.750000      24.000000   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
count            12330.000000    12330.000000             12330.000000   
mean                34.472398       31.731468              1194.746220   
std                140.749294       44.475503              1913.669288   
min                  0.000000        0.000000                 0.000000   
25%                  0.000000        7.000000               184.137500   
50%                  0.000000       18.000000               598.936905   
75%                  0.000000       38.000000              1464.157214   
max               2549.375000      705.000000             63973.522230   

        BounceRates     ExitRates    PageValues    SpecialDay  \
count  12330.000000  12330.000000  12330.000000  12330.000000   
mean       0.022191      0.043073      5.889258      0.061427   
std        0.048488      0.048597     18.568437      0.198917   
min        0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.014286      0.000000      0.000000   
50%        0.003112      0.025156      0.000000      0.000000   
75%        0.016813      0.050000      0.000000      0.000000   
max        0.200000      0.200000    361.763742      1.000000   

       OperatingSystems       Browser        Region   TrafficType  
count      12330.000000  12330.000000  12330.000000  12330.000000  
mean           2.124006      2.357097      3.147364      4.069586  
std            0.911325      1.717277      2.401591      4.025169  
min            1.000000      1.000000      1.000000      1.000000  
25%            2.000000      2.000000      1.000000      2.000000  
50%            2.000000      2.000000      3.000000      2.000000  
75%            3.000000      2.000000      4.000000      4.000000  
max            8.000000     13.000000      9.000000     20.000000

**Choose column [1, 4, 5, 11, 12, 14] and turn into numpy array ``" x "``**

In [7]:
x=shoppers[['Administrative_Duration','ProductRelated','ProductRelated_Duration','OperatingSystems','Browser','Region']]

In [8]:
x=np.array(x)
x

array([[  0.  ,   1.  ,   0.  ,   1.  ,   1.  ,   1.  ],
       [  0.  ,   2.  ,  64.  ,   2.  ,   2.  ,   1.  ],
       [  0.  ,   1.  ,   0.  ,   4.  ,   1.  ,   9.  ],
       ...,
       [  0.  ,   6.  , 184.25,   3.  ,   2.  ,   1.  ],
       [ 75.  ,  15.  , 346.  ,   2.  ,   2.  ,   3.  ],
       [  0.  ,   3.  ,  21.25,   3.  ,   2.  ,   1.  ]])

**Use numpy function to load weight data, bias data and check their shape**

In [9]:
weight_1=np.load('D:/layer_1_weight.npy')
weight_2=np.load('D:/layer_2_weight.npy')

bias_1=np.load('D:/layer_1_bias.npy') 
bias_2=np.load('D:/layer_2_bias.npy')

In [10]:
print('weight_1 shape:',weight_1.shape )
print('weight_2 shape:',weight_2.shape )
print('')
print('bias_1 shape:',bias_1.shape)
print('bias_2 shape:',bias_2.shape)

weight_1 shape: (6, 32)
weight_2 shape: (32, 2)

bias_1 shape: (32,)
bias_2 shape: (2,)


**Use numpy function to compute `" x "` and weight_1 matrix multiplication, and check the shape**

In [17]:
x=x.dot(weight_1)
print(x.shape)

(12330, 32)


**Use numpy function to compute `" x "` and bias_1 matrix addtion, and check the shape**

In [18]:
x=np.add(x,bias_1)
print(x.shape)

(12330, 32)


**Use numpy function to compute `" x "` and weight_2 matrix multiplication, and check the shape**

In [19]:
x=x.dot(weight_2)
print(x.shape)

(12330, 2)


**Use numpy function to compute `" x "` and bias_2 matrix addtion, and check the shape**

In [20]:
x=np.add(x,bias_2)
print(x.shape)

(12330, 2)


**Check if your x is same as below**

In [21]:
x=np.array(x)
x

array([[ -0.42815397,  -0.58708018],
       [ 17.76804854, -12.0093477 ],
       [ -1.07327452,  -3.72237766],
       ...,
       [ 51.70654464, -34.08445513],
       [110.52965928, -73.95802223],
       [  5.45892153,  -4.42243782]])

**Use numpy function to find out each row which one value is bigger, and save it as `" pre "`**

In [22]:
pre=x.argmax(axis=1)
pre

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

**Use numpy function to check if `pre[i]` is the same as `label[i]`, and save it as `" check "`**

In [23]:
check=pre==label
check=check.astype(int)
check

array([[1, 1, 1, ..., 1, 1, 1]])

**Use numpy function to calculate the accuracy**

In [25]:
N=label.shape[1]
accuracy = (label == pre).sum()/N
print('accuracy:',accuracy)

accuracy: 0.8284671532846716
